config/routes.rb
Rails.application.routes.draw do
  get :example, controller: :example, action: :show

  resources :sessions, only: [:new, :create] do
    collection do
      get :logout
    end
  end

  root 'example#show'

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  include Reactivity::Hooks

  belongs_to :user

  private

  def to_reactivity
    {
      id: id,
      username: user.username,
      text: text,
      created_at: created_at
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_auth

  private

  def require_auth
    return if current_user

    redirect_to new_session_path
  end

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end
end

app/controllers/example_controller.rb
class ExampleController < ApplicationController
  def show

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_auth

  def new

  end

  def create
    username = params[:session][:username]

    user = User.create!(username: username)

    cookies.signed[:user_id] = user.id

    redirect_to root_path
  end

  def logout
    cookies.signed[:user_id] = nil

    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/example/show.html.haml
= "Signed in as @#{current_user.username}"
= link_to '(logout)', logout_sessions_path
%br
%br
%textarea#debug{rows: 25, cols: 200}
  Loading...
%br
%br

:javascript
  new Example();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactivityChat</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>